using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using Xunit;

namespace OtdInterop.Tests;

/// <summary>
/// The library's exported surface, written down and checked (#807 Phase 6/7).
/// </summary>
///
/// <remarks>
/// <para>
/// <c>OtdInteropBoundaryTests</c> asserts properties of the boundary — that no public type offers an
/// unmediated write, that the connection is not public, that the capabilities object cannot be cast back.
/// Those are the rules. This is the <em>inventory</em>: every exported type and member, with signatures,
/// so that a change to the surface has to be an act rather than a side effect.
/// </para>
/// <para>
/// The two are not substitutes. A name-based rule cannot notice a new public type that breaks no rule,
/// and an inventory cannot notice a rule being broken by a type that was always there. Phase 6 promised
/// a reviewed snapshot and the boundary tests say in their own summary that they are not it.
/// </para>
/// <para>
/// <b>When this fails:</b> the diff in the failure message is the API change. If it was intended, run the
/// suite with <c>OTDINTEROP_APPROVE_API=1</c> to rewrite <c>PublicApi.txt</c>, and put the rewritten file
/// in the same commit as the change — so review sees the surface move, not just the code.
/// </para>
/// </remarks>
public class PublicApiSnapshotTests
{
    /// <summary>The committed surface and the actual surface are the same.</summary>
    [Fact]
    public void TheExportedSurfaceMatchesTheCommittedSnapshot()
    {
        var actual = Describe(typeof(OtdSession).Assembly);
        var path = SnapshotPath();

        if (Environment.GetEnvironmentVariable("OTDINTEROP_APPROVE_API") == "1")
        {
            File.WriteAllText(path, actual);
            return;
        }

        Assert.True(File.Exists(path), $"No committed snapshot at {path}. Approve one with OTDINTEROP_APPROVE_API=1.");

        var committed = Normalise(File.ReadAllText(path));
        if (Normalise(actual) == committed) return;

        Assert.Fail("The library's public API differs from the committed snapshot.\n\n"
                    + Difference(committed, Normalise(actual))
                    + "\n\nIf this change is intended, re-approve with OTDINTEROP_APPROVE_API=1 and commit "
                    + "PublicApi.txt alongside it.");
    }

    // --- description ----------------------------------------------------------------------------

    private static string Describe(Assembly assembly)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# OtdInterop public API. Generated by PublicApiSnapshotTests; do not hand-edit.");
        sb.AppendLine("# Re-approve with OTDINTEROP_APPROVE_API=1 when a change is intended, and commit");
        sb.AppendLine("# the result in the same change, so review sees the surface move.");
        sb.AppendLine("#");
        sb.AppendLine("# Two exported types are deliberate exceptions to \"the library owns settings writing\":");
        sb.AppendLine("#   AtomicFile    - a general write-then-replace file mechanism.");
        sb.AppendLine("#   SettingsCodec - a general serialize/deserialize mechanism.");
        sb.AppendLine("# Neither reaches the session's active-settings writer, which is internal and mediated");
        sb.AppendLine("# by IOtdSettingsSession. They are kept public because callers legitimately compose");
        sb.AppendLine("# file and serialization operations of their own; the boundary was never a sandbox,");
        sb.AppendLine("# and removing them would not stop in-process code opening a path itself.");
        sb.AppendLine();

        foreach (var type in assembly.GetExportedTypes().OrderBy(t => t.FullName, StringComparer.Ordinal))
        {
            sb.AppendLine(Signature(type));

            foreach (var member in Members(type))
                sb.AppendLine("    " + member);

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string Signature(Type t)
    {
        var kind = t.IsEnum ? "enum"
            : t.IsInterface ? "interface"
            : t.IsValueType ? "struct"
            : "class";

        var bases = new List<string>();
        if (t.BaseType is { } b && b != typeof(object) && b != typeof(ValueType) && b != typeof(Enum))
            bases.Add(Name(b));
        bases.AddRange(t.GetInterfaces().Select(Name).OrderBy(s => s, StringComparer.Ordinal));

        var inherits = bases.Count > 0 ? " : " + string.Join(", ", bases) : "";
        return $"{kind} {Name(t)}{inherits}";
    }

    private static IEnumerable<string> Members(Type t)
    {
        var rows = new List<string>();

        foreach (var c in t.GetConstructors(BindingFlags.Public | BindingFlags.Instance))
            rows.Add($".ctor({Parameters(c)})");

        foreach (var p in t.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
            rows.Add($"{Name(p.PropertyType)} {p.Name} {{ {(p.CanRead ? "get; " : "")}{(p.CanWrite ? "set; " : "")}}}");

        foreach (var e in t.GetEvents(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
            rows.Add($"event {Name(e.EventHandlerType!)} {e.Name}");

        foreach (var f in t.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
            rows.Add(t.IsEnum ? $"{f.Name}" : $"{Name(f.FieldType)} {f.Name}");

        foreach (var m in t.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
        {
            if (m.IsSpecialName) continue;   // property/event accessors, already described above

            rows.Add($"{Name(m.ReturnType)} {m.Name}({Parameters(m)})");
        }

        return rows.OrderBy(s => s, StringComparer.Ordinal);
    }

    private static string Parameters(MethodBase m) =>
        string.Join(", ", m.GetParameters().Select(p =>
            $"{Name(p.ParameterType)} {p.Name}" + (p.HasDefaultValue ? " = default" : "")));

    /// <summary>A stable, readable type name — generics spelled out, no assembly qualification.</summary>
    private static string Name(Type t)
    {
        if (t.IsByRef) return Name(t.GetElementType()!) + "&";
        if (t.IsArray) return Name(t.GetElementType()!) + "[]";

        if (!t.IsGenericType) return t.FullName?.Replace('+', '.') ?? t.Name;

        var def = t.GetGenericTypeDefinition().FullName ?? t.Name;
        var tick = def.IndexOf('`');
        if (tick > 0) def = def[..tick];

        return $"{def.Replace('+', '.')}<{string.Join(", ", t.GetGenericArguments().Select(Name))}>";
    }

    // --- plumbing -------------------------------------------------------------------------------

    /// <summary>
    /// The snapshot beside this source file, not beside the built assembly.
    /// </summary>
    /// <remarks>
    /// Anchored to the compiler's record of where this file is, rather than walked up from
    /// <c>AppContext.BaseDirectory</c>. The walk was the first version and it was wrong: this repository
    /// routinely builds to a redirected output path (the app holds a lock on <c>bin/</c>), and from there
    /// no amount of walking reaches the repository. The committed file is the artifact under review, so
    /// the test has to find that one and not a copy.
    /// </remarks>
    private static string SnapshotPath([CallerFilePath] string here = "") =>
        Path.Combine(Path.GetDirectoryName(here)!, "PublicApi.txt");

    private static string Normalise(string s) => s.Replace("\r\n", "\n").TrimEnd() + "\n";

    private static string Difference(string committed, string actual)
    {
        var was = committed.Split('\n');
        var now = actual.Split('\n');

        var removed = was.Except(now).Where(l => l.Trim().Length > 0).Take(25).ToList();
        var added = now.Except(was).Where(l => l.Trim().Length > 0).Take(25).ToList();

        var sb = new StringBuilder();
        if (removed.Count > 0) sb.AppendLine("REMOVED from the public API:").AppendLine(string.Join("\n", removed.Select(l => "  - " + l.Trim())));
        if (added.Count > 0) sb.AppendLine("ADDED to the public API:").AppendLine(string.Join("\n", added.Select(l => "  + " + l.Trim())));

        return sb.ToString();
    }
}
